services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    profiles:
      - active

  catalog-service:
    build: ./catalog-service
    image: catalog-service
    ports:
      - "8081:8081"
    profiles:
      - dev

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
    profiles:
      - active

volumes:
  pgdata:
