spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgres://localhost:5432/sim_racing_shop_db
spring.datasource.name=fifi
spring.datasource.password=anx00di1
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true